/* 상품카테고리 데이타 */
insert into category values (1, 'CPU');
insert into category values (2, 'RAM');
insert into category values (3, 'MAINBOARD');
insert into category values (4, 'HDD_FDD');
insert into category values (5, 'VGA');
insert into category values (6, 'SOUND');
insert into category values (7, 'MONITOR');
insert into category values (8, 'CDROM');
insert into category values (9, 'COOLER');
insert into category values (10, 'MOUSE');
insert into category values (11, 'CASE');
insert into category values (12, 'POWER');
insert into category values (13, 'KEYBOARD');
insert into category values (14, 'NETWORK');
insert into category values (15, 'SPEAKER');
insert into category values (16, 'SCANNER');
insert into category values (17, 'PRINTER');
insert into category values (18, 'PC CAMERA');
insert into category values (19, 'CD');
insert into category values (20, 'CD CASE');
insert into category values (21, 'INK');
insert into category values (22, 'DESK');
insert into category values (23, 'BRAND PC');
insert into category values (24, 'NOTEBOOK');
insert into category values (25, 'NOTEBOOK ETC');
insert into category values (26, 'Share');
insert into category values (27, 'INTERNET SHARE');
insert into category values (28, 'LANCARD');
insert into category values (29, 'Gender');
insert into category values (30, 'OS');
insert into category values (31, 'TOOL');
insert into category values (32, 'Graphic');
insert into category values (33, 'OFFICE');
insert into category values (34, 'DIGITAL CAMERA');
insert into category values (35, 'PC CAMERA2');
insert into category values (36, 'CAMERA ETC');
insert into category values (37, 'PDA');
insert into category values (38, 'PDA ETC');
insert into category values (39, 'MP3 Player');